version: "3"

services:
  localstack:
    image: localstack/localstack
    ports:
      - '4566-4597:4566-4597'
    environment:
      - EDGE_PORT=4566
      - SERVICES=sqs,sns,dynamodb,iam,s3,lambda,cloudwatch
      - EXTRA_CORS_ALLOWED_ORIGIN=app://.
      - DISABLE_CORS_CHECKS=1
      - DEBUG=1
    volumes:
      - ./localstack/init-scripts:/docker-entrypoint-initaws.d
      - /var/run/docker.sock:/var/run/docker.sock
  crypto-data-digest-lambda:
    image: lfbrienze/crypto-data-digest-lambda:latest
    volumes:
      - ./lambda-files:/lambda-files
    entrypoint: sh -c "cp crypto-robot-data-digest.zip /lambda-files"
  awscli:
    depends_on:
      - crypto-data-digest-lambda
    image: amazon/aws-cli:latest
    volumes:
      - ./lambda-files:/lambda-files
      - ./crypto-data-digest-lambda/init-scripts:/init-scripts/crypto-data-digest-lambda
    entrypoint: sh -c "sh /init-scripts/crypto-data-digest-lambda/01-profile-creation.sh && sh /init-scripts/crypto-data-digest-lambda/02-wait-for-localstack.sh && sh /init-scripts/crypto-data-digest-lambda/03-resources-creation.sh"