version: "3"

services:
  localstack:
    image: localstack/localstack
    ports:
      - '4566-4597:4566-4597'
    environment:
      - EDGE_PORT=4566
      - SERVICES=sqs,sns,dynamodb,iam,s3,lambda,cloudwatch
      - EXTRA_CORS_ALLOWED_ORIGIN=app://.
      - DISABLE_CORS_CHECKS=1
      - DEBUG=1
    volumes:
      - ./init-scripts/localstack:/docker-entrypoint-initaws.d
      - /var/run/docker.sock:/var/run/docker.sock
  crypto-data-digest-lambda:
    image: lfbrienze/crypto-data-digest-lambda
    volumes:
      - ./init-scripts/robot/data-digest:/init-scripts
    entrypoint: sh -c "sh /init-scripts/01-profile-creation.sh && sh /init-scripts/02-wait-for-localstack.sh && sh /init-scripts/03-resources-creation.sh"